// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJHMrj7t7IuZBEH4nwQqvwT-PFweDQ6U',
    appId: '1:73693772352:web:155ea5dfb490924265bda5',
    messagingSenderId: '73693772352',
    projectId: 'test-16718',
    authDomain: 'test-16718.firebaseapp.com',
    storageBucket: 'test-16718.firebasestorage.app',
    measurementId: 'G-MK12KZ4MY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPAdlFsePaW433Gzwos71EdnuMJujeAmc',
    appId: '1:73693772352:android:6c731c09d3c5d16f65bda5',
    messagingSenderId: '73693772352',
    projectId: 'test-16718',
    storageBucket: 'test-16718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjfipZ7pROD7QKk_HKWSy9CVp09rHjW0',
    appId: '1:73693772352:ios:1365dc827a781ab465bda5',
    messagingSenderId: '73693772352',
    projectId: 'test-16718',
    storageBucket: 'test-16718.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAjfipZ7pROD7QKk_HKWSy9CVp09rHjW0',
    appId: '1:73693772352:ios:1365dc827a781ab465bda5',
    messagingSenderId: '73693772352',
    projectId: 'test-16718',
    storageBucket: 'test-16718.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJHMrj7t7IuZBEH4nwQqvwT-PFweDQ6U',
    appId: '1:73693772352:web:94bbe6a9a25c7a1965bda5',
    messagingSenderId: '73693772352',
    projectId: 'test-16718',
    authDomain: 'test-16718.firebaseapp.com',
    storageBucket: 'test-16718.firebasestorage.app',
    measurementId: 'G-KLGE4YETEN',
  );

}
